title = "world"

[scene]
hdri = "road.jpg"

[mesh]
file = "cornell.obj"
material = "diffuse"
texture = "cornell.png"

[lights]
position = [5.0, 0.0, 6.0]
colour = [1.0, 0.0, 0.0]
type = "directional"

[camera]
position = [0.0, 1.2, 2.3]
lookat = [0.0, 1.2, 0.0]
fov = 50.0
dimensions = [720, 720]
tile_size = 16 #must be a factor of the dimensions