title = "world"

[mesh]
file = "teapot.obj"
material = "diffuse"
texture = "grey.png"

[lights]
position = [5.0, 0.0, 6.0]
colour = [1.0, 0.0, 0.0]
type = "directional"

[camera]
position = [1.5, 2.7, 2.8]
lookat = [0.0, 0.9, 0.0]
fov = 50.0
dimensions = [1280, 720]
tile_size = 16 #must be a factor of the dimensions